# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Candy < Formula
  desc "Zero-config reverse proxy server"
  homepage "https://github.com/owenthereal/candy"
  version "0.6.1"
  license "Apache 2.0"

  depends_on "nss"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/owenthereal/candy/releases/download/v0.6.1/candy_darwin_amd64.tar.gz"
      sha256 "2128a28b636b9310e2b149981b658d64818a7c757dcc266bb504e91f6d48caf9"

      def install
        bin.install "bin/candy"
        prefix.install_metafiles
        etc.install "example/candyconfig" => "candyconfig"
        (etc/"resolver").install "example/mac/candy-test" => "candy-test"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/owenthereal/candy/releases/download/v0.6.1/candy_darwin_arm64.tar.gz"
      sha256 "77b4f3b71c0d32ac60d4f177b27b81d68031b0f1b5116c6a3146efac5309d17b"

      def install
        bin.install "bin/candy"
        prefix.install_metafiles
        etc.install "example/candyconfig" => "candyconfig"
        (etc/"resolver").install "example/mac/candy-test" => "candy-test"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/owenthereal/candy/releases/download/v0.6.1/candy_linux_amd64.tar.gz"
      sha256 "82540774c6546000d86d9f98cbf15975b7f67aa13b33c3c8055f87a6d4cb41d8"

      def install
        bin.install "bin/candy"
        prefix.install_metafiles
        etc.install "example/candyconfig" => "candyconfig"
        (etc/"resolver").install "example/mac/candy-test" => "candy-test"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/owenthereal/candy/releases/download/v0.6.1/candy_linux_armv6.tar.gz"
      sha256 "5f6ea1707569b72c60ac4d4f6c1adc3283d50265e16bc319d44452e3b80ef66e"

      def install
        bin.install "bin/candy"
        prefix.install_metafiles
        etc.install "example/candyconfig" => "candyconfig"
        (etc/"resolver").install "example/mac/candy-test" => "candy-test"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/owenthereal/candy/releases/download/v0.6.1/candy_linux_arm64.tar.gz"
      sha256 "93e82adb24e3b40a7d2fc2885141db6c2a0d6e0a1fd4120944577c3b26bddb46"

      def install
        bin.install "bin/candy"
        prefix.install_metafiles
        etc.install "example/candyconfig" => "candyconfig"
        (etc/"resolver").install "example/mac/candy-test" => "candy-test"
      end
    end
  end

  head "https://github.com/owenthereal/candy.git"

  def caveats
    <<~EOS
      <<~EOS
        To finish the installation, you need to create a DNS resolver file
        in /etc/resolver/YOUR_DOMAIN. Creating the /etc/resolver directory
        and the config file requires superuser privileges. You can set things
        up with an one-liner

            sudo candy setup

        Alternatively, you can execute the following bash script

            sudo mkdir -p /etc/resolver && \\
              sudo chown -R $(whoami):$(id -g -n) /etc/resolver && \\
              cp #{etc/"resolver/candy-test"} /etc/resolver/candy-test

        To have launchd start Candy now and restart at login

            brew services start candy

        Or, if you don't want/need a background service you can just run

            candy run

        A sample Candy config file is in #{etc/"candyconfig"}. You can
        copy it to your home to override Candy's default setting

            cp #{etc/"candyconfig"} ~/.candyconfig
      EOS
    EOS
  end

  service do
    run [opt_bin/"candy", "launch", "--dns-local-ip"]
    keep_alive true
    run_at_load true
    sockets "Socket" => "tcp://0.0.0.0:80", "SocketTLS" => "tcp://0.0.0.0:443"
    working_dir HOMEBREW_PREFIX
    log_path var/"log/candy/output.log"
    error_log_path var/"log/candy/output.log"
  end

  test do
    http = free_port
    https = free_port
    dns = free_port
    admin = free_port

    mkdir_p testpath/".candy"
    (testpath/".candy/app").write(admin)

    (testpath/"candyconfig").write <<~EOS
      {
        "domain": ["brew-test"],
        "http-addr": "127.0.0.1:#{http}",
        "https-addr": "127.0.0.1:#{https}",
        "dns-addr": "127.0.0.1:#{dns}",
        "admin-addr": "127.0.0.1:#{admin}",
        "host-root": "#{testpath/".candy"}"
      }
    EOS
    puts shell_output("cat #{testpath/"candyconfig"}")

    fork do
      exec bin/"candy", "run", "--config", testpath/"candyconfig"
    end

    sleep 2

    assert_match "\":#{http}\"", shell_output("curl -s http://127.0.0.1:#{admin}/config/apps/http/servers/candy/listen/0")
    assert_match "\":#{https}\"", shell_output("curl -s http://127.0.0.1:#{admin}/config/apps/http/servers/candy/listen/1")
    assert_match "127.0.0.1", shell_output("dig +short @127.0.0.1 -p #{dns} app.brew-test")
  end
end
